# Generated by Django 5.0.6 on 2024-07-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='tienda.CartItem', to='tienda.product'),
        ),
    ]
